### ISSUE TITLE
Persisten storage of yetiforce

### ISSUE THREAD

**Issue by SunnySs** [efernau/Docker-YetiForceCRM#10]
The data stored inside the yetiforce service seems not to be persistent at the moment. Is it possible to mount the data to be persistent to the host system so that the data won't be lost after removing the yetiforce container? Thank you!

**Comment by efernau** [comment]
Yeah, sure. docker-compose allows to mount volumes with e.g. relative paths by using ./ which points to the folder where the compose file is located.


```
version: "3.3"

services:
  mysql:
    image: mysql:5.6
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: yetiforce
      MYSQL_DATABASE: yetiforce
      MYSQL_USER: yetiforce
      MYSQL_PASSWORD: yetiforce
    restart: always
    ports:
      - "3306:3306"
    command: mysqld --sql_mode="STRICT_TRANS_TABLE" --sql_mode="ONLY_FULL_GROUP_BY"  --character-set-server="utf8" --collation-server="utf8_unicode_ci" --max-allowed-packet="1073741824" --innodb_lock_wait_timeout="600"

  yetiforce:
    links:
      - mysql
    build: 5.2.0
    volumes:
      - ./html:/var/www/html
    ports:
      - "8000:80"
    restart: always
```
